In [11]:
import numpy as np
import pandas as pd

In [5]:
#1

# Create a NumPy array with numbers from 1 to 10
arr = np.arange(1, 11)

# Reshape the array into a 2x5 matrix
matrix = arr.reshape(2, 5)

# Print the reshaped matrix
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [7]:
#2

# Create a NumPy array with numbers from 1 to 20
arr = np.arange(1, 21)

# Extract elements between the 5th and 15th index 
extracted_elements = arr[5:15]

# Print the extracted elements
print(extracted_elements)

[ 6  7  8  9 10 11 12 13 14 15]


In [13]:
#3

# Create a Pandas Series
fruit_series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})

# Add a new item to the series
fruit_series['pears'] = 4

# Print the updated series
print(fruit_series)

apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [15]:
#4
#Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data. 
# Create a dictionary with data
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Emma', 'Frank', 'Grace', 'Hannah', 'Isaac', 'Jack'],
    'age': [25, 30, 22, 28, 35, 40, 27, 23, 31, 29],
    'gender': ['Female', 'Male', 'Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Male']
}

# Create a DataFrame
df = pd.DataFrame(data)


print(df)

      name  age  gender
0    Alice   25  Female
1      Bob   30    Male
2  Charlie   22    Male
3    David   28    Male
4     Emma   35  Female
5    Frank   40    Male
6    Grace   27  Female
7   Hannah   23  Female
8    Isaac   31    Male
9     Jack   29    Male


In [ ]:
#5
# Add a new column to the data frame created aboove, called occupation.
#The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.

In [17]:
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 
                    'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']

# Display the updated DataFrame
print(df)

      name  age  gender  occupation
0    Alice   25  Female  Programmer
1      Bob   30    Male     Manager
2  Charlie   22    Male     Analyst
3    David   28    Male  Programmer
4     Emma   35  Female     Manager
5    Frank   40    Male     Analyst
6    Grace   27  Female  Programmer
7   Hannah   23  Female     Manager
8    Isaac   31    Male     Analyst
9     Jack   29    Male  Programmer


In [ ]:
#6
#Select the rows of the dataframe where the age is greater than or equal to 30.

In [25]:
selected_age=df[df['age']>=30]

print(selected_age)

    name  age  gender occupation
1    Bob   30    Male    Manager
4   Emma   35  Female    Manager
5  Frank   40    Male    Analyst
8  Isaac   31    Male    Analyst


In [ ]:
#7
#Convert this dataframe to a csv file and read that csv file, finally display the contents.

In [29]:
df.to_csv("python_7.csv", index=False)

# Read the CSV file
df_read = pd.read_csv("python_7.csv")

print(df_read)

      name  age  gender  occupation
0    Alice   25  Female  Programmer
1      Bob   30    Male     Manager
2  Charlie   22    Male     Analyst
3    David   28    Male  Programmer
4     Emma   35  Female     Manager
5    Frank   40    Male     Analyst
6    Grace   27  Female  Programmer
7   Hannah   23  Female     Manager
8    Isaac   31    Male     Analyst
9     Jack   29    Male  Programmer
